apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: admin
    secureJsonData:
      password: password123
    jsonData:
      database: monitoring_db
      sslmode: disable
    isDefault: true
